### ISSUE TITLE
Retrieving the compiled HTML

### ISSUE THREAD

**Issue by Mashiane** [vberlier/mjml-web#4]
Hi there

I am trying your library via the browser. How do I retrieve the compiled html from mjml?

I'm new to this and trying to find my way.

Thanks.

**Comment by vberlier** [comment]
You should probably make sure you're familiar with mjml first. Their documentation should explain everything you need to know. In any case, I made a small demo on codepen that should help you get started: https://codepen.io/vberlier/pen/xxVqMdP
